### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-cristinatato#1]
Cool job @cristinatato  !!!

Here you have some tips to improve the exercise:

### JavaScript

- [x] Define the logic to make the counter work using a variable
- [x] Remember to convert input value string to a number

### JavaScript - Good practices

- [x] Use `===` instead of `==` for comparisons

### HTML

- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by cristinatato** [comment]
HI oneeydman! I made some changes to improve the exercise and i fix everything you told me.
Best regards!

**Comment by cristinatato** [comment]
@oneeyedman i think you haven't read this yet! Sorry!
